version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:[TAG]
   steps:
     - checkout
     - run:
         name: test
         command: |
           npm install
           npm test
           npm lint
