const data = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin sollicitudin sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec libero eros, finibus elementum venenatis et, aliquam at diam. Curabitur lectus velit, rutrum eget ultrices non, faucibus ac dolor. Sed venenatis dignissim efficitur. Curabitur rutrum nunc non ante mattis, id porta metus ullamcorper. Aliquam velit ipsum, varius sit amet dignissim quis, tristique non dui. Aliquam dignissim egestas facilisis. Nullam quis cursus enim. Aenean dui nisl, faucibus sed dui ac, vehicula aliquam erat. Nulla sodales est velit, ac congue metus mattis et. Sed et tellus sit amet felis elementum volutpat sit amet nec sem. In eget nulla ligula. Maecenas non diam ut metus varius convallis. Donec sed nunc eget sapien ullamcorper condimentum at non neque. Etiam sapien neque, consectetur in dolor in, tempor sagittis sem.',

'Fusce pretium, risus consectetur vehicula pharetra, nisl purus eleifend eros, in gravida risus lectus a nisi. Mauris ut scelerisque libero. Quisque sem est, condimentum non nibh et, pulvinar consectetur quam. Nulla rutrum arcu efficitur leo gravida, nec tristique erat convallis. Donec luctus imperdiet dignissim. Aenean lectus odio, luctus et leo in, sodales hendrerit mauris. Nulla facilisi. Morbi convallis sollicitudin dapibus. Fusce non luctus ante.',

'Suspendisse ut feugiat odio, in ullamcorper nulla. Quisque vestibulum quam ut feugiat finibus. Ut aliquet sapien ut aliquam vulputate. Phasellus sed nisl tempus, rhoncus lacus vitae, accumsan ipsum. Ut aliquam vulputate odio a scelerisque. Cras volutpat risus egestas neque cursus, eget sodales velit condimentum. Suspendisse sit amet sollicitudin nisi. Maecenas vel dictum augue. In sit amet tempor est. Donec aliquam scelerisque nulla, vel laoreet elit pellentesque id. Fusce elementum turpis a sollicitudin porta. Fusce erat nisi, sodales lobortis felis non, ornare tempor erat. Sed egestas est nec placerat dignissim. In dapibus est id blandit hendrerit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras id velit tellus.',
]

export default data;
